spring:
  server:
    port: 8080

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
    url: jdbc:mysql://127.0.0.1:3306/mybatisplusdemo?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: jin1997c#
